image: Visual Studio 2017

build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1 -Configuration Release

test: off

artifacts:
  - path: 'artifacts\*'

deploy:
  provider: Environment
  name: github
  on:
    APPVEYOR_REPO_TAG: true  